### ISSUE TITLE
Attest function gives response of encoded string

### ISSUE THREAD

**Issue by ziwenzhao** [karandpr/cordova-plugin-android-safetynet#2]
The attest function gives back a response of long encoded string (which cannot be decoded by base64) instead of a jws result as expected.

**Comment by karandpr** [comment]
@ziwenzhao When I created the module , I used `npm`'s `jws` to decode the string server side.
```
const jws = require('jws');
let decodedJSON = jws.decode(req.body.jws);
```
Let me check if something has changed. 
Cheers !

**Comment by ziwenzhao** [comment]
Thanks a lot! JWS.decode() works very well. Thank you for your response.

**Comment by karandpr** [comment]
Nice to hear that ! I will close the issue :)
