### ISSUE TITLE
sample harmful apps which gets detected in listHarmfulApps API

### ISSUE THREAD

**Issue by kiranitian** [karandpr/cordova-plugin-android-safetynet#3]
Hi, we are trying to test verify apps feature. But we are not getting any harmful apps list,  Could you please let us know any harmful app names so that we can test the scenario?

Thanks in Advance.
Kiran

**Comment by kiranitian** [comment]
Found the application from the below link, which is coming in the list.
https://kingroot.en.uptodown.com/android

**Comment by karandpr** [comment]
Hey Kiran ,
I have a personal list of harmful apps.
https://gist.github.com/karandpr/5033af97fc328a852d55a0bdc008ef4c

These apps should flag listHarmfulApps.
